export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/customers/index',
    'pages/customers/detail/index',
    'pages/customers/form/index',
    'pages/customers/follow-up/index',
    'pages/properties/index',
    'pages/properties/detail/index',
    'pages/properties/form/index',
    'pages/properties/ai-copy/index',
    'pages/services/index',
    'pages/services/form/index',
    'pages/admin/providers/index',
    'pages/admin/providers/form/index',
    'pages/profile/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '章鱼经纪人',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#8c8c8c',
    selectedColor: '#1890ff',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/customers/index',
        text: '客户管理',
        iconPath: './assets/tabbar/users.png',
        selectedIconPath: './assets/tabbar/users-active.png',
      },
      {
        pagePath: 'pages/properties/index',
        text: '房源管理',
        iconPath: './assets/tabbar/home.png',
        selectedIconPath: './assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/services/index',
        text: '生活服务',
        iconPath: './assets/tabbar/heart.png',
        selectedIconPath: './assets/tabbar/heart-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      },
    ],
  },
})
