export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/login/index',
    'pages/customers/index',
    'pages/customers/detail/index',
    'pages/customers/form/index',
    'pages/customers/follow-up/index',
    'pages/properties/index',
    'pages/properties/detail/index',
    'pages/properties/form/index',
    'pages/rent-bills/form/index',
    'pages/services/index',
    'pages/services/form/index',
    'pages/admin/providers/index',
    'pages/admin/providers/form/index',
    'pages/profile/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '章鱼经纪人',
    navigationBarTextStyle: 'black',
    backgroundColor: '#f7f8fa',
  },
  tabBar: {
    color: '#9ca3af',
    selectedColor: '#1e3a8a',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: './assets/tabbar/home.png',
        selectedIconPath: './assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/customers/index',
        text: '客户',
        iconPath: './assets/tabbar/users.png',
        selectedIconPath: './assets/tabbar/users-active.png',
      },
      {
        pagePath: 'pages/properties/index',
        text: '房源',
        iconPath: './assets/tabbar/building.png',
        selectedIconPath: './assets/tabbar/building-active.png',
      },
      {
        pagePath: 'pages/services/index',
        text: '服务',
        iconPath: './assets/tabbar/heart.png',
        selectedIconPath: './assets/tabbar/heart-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      },
    ],
  },
  style: 'v2',
  sitemapLocation: 'sitemap.json',
  lazyCodeLoading: 'requiredComponents',
})
